name: Build Project

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Project
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

