name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build and Deploy
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        # Add your build/deploy commands here
        echo "GROQ_API_KEY is configured"