name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build and Deploy
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        # Add your build/deploy commands here
        echo "GROQ_API_KEY is configured"